In [16]:
import pandas as pd

In [27]:
url ="C:\\Users\\Gyameah\Downloads\\AB_NYC_2019.csv\\AB_NYC_2019.csv"
df = pd.read_csv(url)
df.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,2539,Clean & quiet apt home by the park,2787,John,Brooklyn,Kensington,40.64749,-73.97237,Private room,149,1,9,2018-10-19,0.21,6,365
1,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,225,1,45,2019-05-21,0.38,2,355
2,3647,THE VILLAGE OF HARLEM....NEW YORK !,4632,Elisabeth,Manhattan,Harlem,40.80902,-73.94190,Private room,150,3,0,NaN,NaN,1,365
3,3831,Cozy Entire Floor of Brownstone,4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,89,1,270,2019-07-05,4.64,1,194
4,5022,Entire Apt: Spacious Studio/Loft by central park,7192,Laura,Manhattan,East Harlem,40.79851,-73.94399,Entire home/apt,80,10,9,2018-11-19,0.10,1,0

In [28]:
df.shape 
df.info() 
df.isnull().sum() 
df.duplicated().sum()

<class 'pandas.DataFrame'>
RangeIndex: 48895 entries, 0 to 48894
Data columns (total 16 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              48895 non-null  int64
 1   name                            48879 non-null  str
 2   host_id                         48895 non-null  int64
 3   host_name                       48874 non-null  str
 4   neighbourhood_group             48895 non-null  str
 5   neighbourhood                   48895 non-null  str
 6   latitude                        48895 non-null  float64
 7   longitude                       48895 non-null  float64
 8   room_type                       48895 non-null  str
 9   price                           48895 non-null  int64
 10  minimum_nights                  48895 non-null  int64
 11  number_of_reviews               48895 non-null  int64
 12  last_review                     38843 non-null  str
 13  reviews_per_month               38843 non-null  float64
 14  calculated_host_listings_count  48895 non-null  int64
 15  availability_365                48895 non-null  int64
dtypes: float64(3), int64(7), str(6)
memory usage: 9.9 MB

np.int64(0)

In [29]:
df = df.drop_duplicates() 
# fix a type, for example a price stored as text: 
# df["price"] = df["price"].str.replace("$", "").astype(float)

In [35]:
df = pd.read_csv(r"C:\Users\Gyameah\Downloads\AB_NYC_2019.csv\AB_NYC_2019.csv")

In [36]:
df.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,2539,Clean & quiet apt home by the park,2787,John,Brooklyn,Kensington,40.64749,-73.97237,Private room,149,1,9,2018-10-19,0.21,6,365
1,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,225,1,45,2019-05-21,0.38,2,355
2,3647,THE VILLAGE OF HARLEM....NEW YORK !,4632,Elisabeth,Manhattan,Harlem,40.80902,-73.94190,Private room,150,3,0,NaN,NaN,1,365
3,3831,Cozy Entire Floor of Brownstone,4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,89,1,270,2019-07-05,4.64,1,194
4,5022,Entire Apt: Spacious Studio/Loft by central park,7192,Laura,Manhattan,East Harlem,40.79851,-73.94399,Entire home/apt,80,10,9,2018-11-19,0.10,1,0

In [37]:
df.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
48890    False
48891    False
48892    False
48893    False
48894    False
Length: 48895, dtype: bool

In [38]:
df["reviews_per_month"] = df["reviews_per_month"].fillna(0)

In [39]:
df["name"] = df["name"].fillna("Unknown")
df["host_name"] = df["host_name"].fillna("Unknown")

In [40]:
df["last_review"] = pd.to_datetime(df["last_review"], errors="coerce")

In [ ]:
Missing values
   - name               → 16 rows empty
   - host_name          → 21 rows empty
   - last_review        → 10,052 rows empty
   - reviews_per_month  → 10,052 rows empty

. Duplicates
    0 exact duplicate rows (nothing to clean here)

. Wrong data type
    last_review was stored as plain text instead of a real date

WHAT I DID TO FIX IT

1. Removed exact duplicates
    df = df.drop_duplicates()
    No change

2. Filled the few missing names
    df["name"] = df["name"].fillna("Unknown")
   df["host_name"] = df["host_name"].fillna("Unknown")

3. Converted last_review to real dates
    df["last_review"] = pd.to_datetime(df["last_review"], errors="coerce")
    Left the missing ones as empty. 


4. Filled reviews_per_month
   df["reviews_per_month"] = df["reviews_per_month"].fillna(0)
   Zero reviews means rate of zero reviews per month